apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - command:
        - ./hello
        env:
        - name: PORT
          value: "80"
        image: image-name-replaced-with-kustomize
        name: hello
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 10m
            memory: 32Mi
          requests:
            cpu: 5m
            memory: 16Mi
