apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodbye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goodbye
  template:
    metadata:
      labels:
        app: goodbye
    spec:
      containers:
      - name: goodbye
        image: image-name-replaced-with-kustomize
        command: ["./goodbye"]
        ports:
        - name: http
          containerPort: 80
        env:
        - name: PORT
          value: 80
        resources:
          requests:
            memory: "16Mi"
            cpu: "5m"
          limits:
            memory: "32Mi"
            cpu: "10m"
