apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodbye
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goodbye
  template:
    metadata:
      labels:
        app: goodbye
    spec:
      containers:
      - command:
        - ./goodbye
        env:
        - name: PORT
          value: "80"
        image: image-name-replaced-with-kustomize
        name: goodbye
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 10m
            memory: 32Mi
          requests:
            cpu: 5m
            memory: 16Mi
