name: Build and Push Docker Image

on:
  push:
    paths:
      - '**/*.go'
      - 'build/Dockerfile'
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/Dockerfile  # Path to your Dockerfile
          tags: desaias/argocd-demo-apps:latest
          platforms: linux/amd64,linux/arm64
          push: true
